services:
  redis:
    image: redis:7.2-alpine
    container_name: rate-guard-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rate-guard:
    build: .
    container_name: rate-guard
    ports:
      - "50051:50051"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
