// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: ratelimit/v1/ratelimit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                        // id do cliente, ex: tenant_id ou user_id
	LimitId       string                 `protobuf:"bytes,2,opt,name=limit_id,json=limitId,proto3" json:"limit_id,omitempty"` // tipo de serviço utilizado para o ratelimiter(login, search, etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_ratelimit_v1_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_v1_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateLimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRateLimitRequest) GetLimitId() string {
	if x != nil {
		return x.LimitId
	}
	return ""
}

type CheckRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                 // se a requisição foi permitida
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`                             // quantidade de requisições restantes
	RetryAfterMs  int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // tempo em milissegundos para tentar novamente (0 se allowed=true)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_ratelimit_v1_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_v1_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_ratelimit_v1_ratelimit_proto protoreflect.FileDescriptor

const file_ratelimit_v1_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x1cratelimit/v1/ratelimit.proto\x12\fratelimit.v1\"D\n" +
	"\x15CheckRateLimitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\blimit_id\x18\x02 \x01(\tR\alimitId\"v\n" +
	"\x16CheckRateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs2o\n" +
	"\x10RateLimitService\x12[\n" +
	"\x0eCheckRateLimit\x12#.ratelimit.v1.CheckRateLimitRequest\x1a$.ratelimit.v1.CheckRateLimitResponseB3Z1github.com/vhgomes/rate-guard/pkg/pb/ratelimit/v1b\x06proto3"

var (
	file_ratelimit_v1_ratelimit_proto_rawDescOnce sync.Once
	file_ratelimit_v1_ratelimit_proto_rawDescData []byte
)

func file_ratelimit_v1_ratelimit_proto_rawDescGZIP() []byte {
	file_ratelimit_v1_ratelimit_proto_rawDescOnce.Do(func() {
		file_ratelimit_v1_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelimit_v1_ratelimit_proto_rawDesc), len(file_ratelimit_v1_ratelimit_proto_rawDesc)))
	})
	return file_ratelimit_v1_ratelimit_proto_rawDescData
}

var file_ratelimit_v1_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimit_v1_ratelimit_proto_goTypes = []any{
	(*CheckRateLimitRequest)(nil),  // 0: ratelimit.v1.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil), // 1: ratelimit.v1.CheckRateLimitResponse
}
var file_ratelimit_v1_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.v1.RateLimitService.CheckRateLimit:input_type -> ratelimit.v1.CheckRateLimitRequest
	1, // 1: ratelimit.v1.RateLimitService.CheckRateLimit:output_type -> ratelimit.v1.CheckRateLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ratelimit_v1_ratelimit_proto_init() }
func file_ratelimit_v1_ratelimit_proto_init() {
	if File_ratelimit_v1_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelimit_v1_ratelimit_proto_rawDesc), len(file_ratelimit_v1_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimit_v1_ratelimit_proto_goTypes,
		DependencyIndexes: file_ratelimit_v1_ratelimit_proto_depIdxs,
		MessageInfos:      file_ratelimit_v1_ratelimit_proto_msgTypes,
	}.Build()
	File_ratelimit_v1_ratelimit_proto = out.File
	file_ratelimit_v1_ratelimit_proto_goTypes = nil
	file_ratelimit_v1_ratelimit_proto_depIdxs = nil
}
